Alterações
SQUAD-1/FC-Services pull request #88
Opened 2023-05-31 20:23 UTC by CleytonLu

2023-06-04 08:47 UTC, welllucky commented on src/Pages/Chamados/TelaDeConfirmação/index.tsx
> +	console.log("file", file);
tirar o console.log

2023-06-04 08:48 UTC, welllucky approved these changes

2023-06-04 08:56 UTC, welllucky requested changes
Tirar os console.log que você colocou no código e corrigir a distância dos botões de ação da tela de abrir chamado

2023-06-04 09:01 UTC, welllucky commented on src/Pages/Chamados/TelaDeConfirmação/index.tsx
> +	console.log("file", file);
O chamado não apresenta mais o modal de confirmação, muito menos redireciona o usuário para a tela de chamado.
Atualmente não tem como acessar a tela de chamado. Aproveita e corrige os bugs do fluxo de abrir chamado até ver o chamado, tá horrível

2023-06-05 01:51 UTC, CleytonLu commented
Finalização das atividades de integração com api de tela do chamado e de Mídia, reirecionamento dos cards de home, para tela do chamado, e ajustes no componente mídia.

2023-06-05 03:15 UTC, welllucky approved these changes

2023-06-05 03:15 UTC, merged